### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by ericgaspar**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Review by alexAubin — APPROVED** [review]

**Comment by vcorreze** [comment]
Hello
I tried to update opensondage on my server to fix the bug, but it doesn't work

First point, the update doesn't regen the config. 
When I try 'yunohost tools regen-conf opensondage' it fails, I didn't find the complete log

I updated manually my config.php to put my main domain (`cat /etc/yunohost/current_host`) in smtp_options/host but this doesn't work too.

The log /var/log/nginx/$domain-error.log says : 
```
 2024/02/17 15:12:48 [error] 556565#556565: *43904 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught│
 PHPMailer\PHPMailer\Exception: SMTP Error: The following recipients failed: $(myadress): <($my_ynh_user)>: │
Sender address rejected: not logged in
```

If this can help...

**Comment by rodinux** [comment]
for me changing the user admin_user the mail with `opensondage` have resolve the issue

```
// Database administrator email
const ADRESSEMAILADMIN = 'opensondage@sondage.domain.tld';
```
and restart php8.2-fpm
```
yunohost service restart php8.2-fpm
```

**Comment by vcorreze** [comment]
Yes, changing the CONST ADRESSEMAILADMIN to `opensondage@mydomain.tld` worked.
Thanks!

**Pull request merged**
