### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by maniackcrudelis**
## Problem
- 

## Solution
- *Upgrade to 1.0.3 and total rewriting*

## PR Status
Work finished. Package_check, basic tests and upgrade from last version OK.  
Could be reviewed and tested.

## Validation
---
*Minor decision*
- [x] **Upgrade previous version** : Maniack C
- [x] **Code review** : frju365
- [x] **Approval (LGTM)** : Maniack C
- [x] **Approval (LGTM)** : frju365
- [x] **CI succeeded** : [Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/opensondage_ynh%20testing%20(Official)/)  
When the PR is mark as ready to merge, you have to wait for 3 days before really merge it.

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
@Jibec, this PR doesn't work. Can you have a look ?

**Comment by maniackcrudelis** [comment]
Upgrade ok, LGTM

**Comment by Jibec** [comment]
can we please merge this?

**Comment by frju365** [comment]
Will be merged in 3 days.

**Comment by Jibec** [comment]
kind remember

**Comment by alexAubin** [comment]
Congratz on level 7 \o/ https://ci-apps.yunohost.org/jenkins/job/opensondage%20(Official)/22/consoleFull

**Pull request merged**
