### PR TITLE
Package upgrade

### PR DESCRIPTION
**Pull request by maniackcrudelis**
## Problem
- *Global upgrade of the package.*
- *Add a change_url script*
- *Can access the admin part of the poll without YNH account*

## PR Status
- [x] Code finished.
- [x] Tested with Package_check.
- [x] Fix or enhancement tested.
- [x] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [x] **Code review** : Kay0u
- [x] **Approval (LGTM)** : JimboJoe
- [x] **Approval (LGTM)** : Kay0u
- **CI succeeded** : 
[Build Status](https://ci-apps-hq.yunohost.org/jenkins/job/opensondage_ynh%20PR45/)  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by kay0u** [comment]
Maybe we should wait  #47 before merging this one?

**Comment by maniackcrudelis** [comment]
@kay0u, could you please confirm that I didn't messed up your work with the commit to resolve the conflict.

**Comment by kay0u** [comment]
To me it's ok, I'll update the change URL script too.

**Comment by kay0u** [comment]
> @kay0u, could you please confirm that I didn't messed up your work with the commit to resolve the conflict.

I just update with getops, but to me it's ok. (Sorry for these shitty commits)
I've updated change_url too, if you can take a look :-)

**Comment by maniackcrudelis** [comment]
Looks ok, let's merge in 3 days.

**Pull request merged**
