### PR TITLE
New Permission System

### PR DESCRIPTION
**Pull request by kay0u**
## Problem
- *Description of why you made this PR*

## Solution
- *And how you fix that*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [ ] **Code review** : 
- [ ] **Approval (LGTM)** : 
- [ ] **Approval (LGTM)** : 
- **CI succeeded** : 
[Build Status](https://ci-apps-hq.yunohost.org/jenkins/job/opensondage_ynh%20PR59/)  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by zamentur** [comment]
does this PR fix https://forum.yunohost.org/t/opensondage-admin-exposed/16614 ?

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
> does this PR fix https://forum.yunohost.org/t/opensondage-admin-exposed/16614 ?

I can't access the private topic... `Oops! That page doesn’t exist or is private`

**Comment by ericgaspar** [comment]
This PR seems to resolve the exposed admin issue...

Capture d’écran 2021-07-22 à 16 41 24

@kay0u Do you know how to resolve `Install (private)`? 🤔

**Comment by alexAubin** [comment]
Hmpf I guess the CI fails because it expects that accessing the app url should result in being redirected to the SSO (because it's private) ... but it doesn't because for this app, being private only means that the poll creation page is accessible only to logged-in users ... zblerg

**Pull request merged**
